### ISSUE TITLE
Dealing with Flat Regions

### ISSUE THREAD

**Issue by maljovec** [maljovec/topopy#10]
Flat regions can cause a few issues with the MorseSmaleComplex. Here we can consider using two different methods one involves perturbing the data and the second involves sorting the data in a meaningful way.

Refer to this email from Yarden for reference:

> Let's assume that delta = min( | p_j[d] - p_k[d] )| for all j, k  for all dimension d.
> 
> If we perturbate each point i by eps_i such that eps_i[d] < delta than 
> 1) no two points can switch order
> 2) Then in the final results if the difference between any two persistence levels is less than delta than this mean that you can merge them. So if A and B merge into A in P_i (level i) and A and C merge into C at P_i+1 such that P_i+1 - P_i < delta than you ignore P_i and report that A merge to C and B merge to C at P_i+1 and forget P_i

**Comment by orpheus92** [comment]
I did not quite understand the 2nd part. One problem I might have with flat region would be if Min A merges to Min B and Min B merges to Min C at same persistence level, there might be an issue when perturbing the hierarchy.

**Comment by orpheus92** [comment]
I guess there should be an internal order deciding the merging order when two or more merges occur at same level.

**Comment by maljovec** [comment]
I believe simulation of simplicity should already be handling this problem. I am going to close this issue.
